
RUTA_DINO_CAMINANDO = "media/dino/caminando/caminando_0"
RUTA_DINO_REPOSO = "media/dino/reposo/reposo_0"
RUTA_DINO_MURIENDO ="media/dino/muriendo/muriendo_0"
RUTA_IMG_FONDO = "media/fondo.jpg"


ESCALA = (70, 80)


ALTO_PANTALLA = 600
ANCHO_PANTALLA = 800
TAMANIO_PANTALLA = (ALTO_PANTALLA, ANCHO_PANTALLA)


POSICION_J_Y = ALTO_PANTALLA - 100
POSICION_J_X = 400


# Colores
COLOR_PLATAFORMA = (100, 100, 100)  # Gris oscuro
COLOR_PUENTE = (0, 0, 0)  # Negro


VELOCIDAD_CRECE_PUENTE = 5
VELOCIDAD_DESPLAZAMIENTO_PANTALLA = 5
VELOCIDAD_ANIMACION = 0.2



